### ISSUE TITLE
Develop course slides

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/package-development-course#30]

**Comment by dgkeyes** [comment]
@malcolmbarrett I've been consolidating functions I've put in several packages into a single one. You can install [this package](https://github.com/rfortherestofus/rfortherestofus), which has the most recent version of the slide templatel.

**Comment by malcolmbarrett** [comment]
Course package: https://github.com/emptyfield-ds/rpkg.workshop
* Installs all course dependencies and wraps `use_course()` to download materials

Currently, rendered, student-facing repos are hosted at https://github.com/emptyfield-ds. We could move them to this account but it's hidden by the course package anyway.

* There's a rendered `slides.pdf` file here
* For modules 3-8, each repo is itself an R package. Students will work on a custom package, with each module repo serving as a checkpoint that contains all the expected work of the previous module, allowing students to continue on even if something isn't quite set up correctly in their attempt at the exercises.
* Each repo contains `exercises.Rmd` with a list of your-turns

The raw materials are here currently: https://github.com/emptyfield-ds/r_teaching_warehouse/. We can move them here when I'm done but it's a bit easier for me to iterate this way.

* You can see the .Rmd file of the slides here

1. Welcome:
* No slides
2. Whole Game
* Rendered material: https://github.com/emptyfield-ds/r_packages_whole_game
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_whole_game
3. R Packages: Setup
* Rendered material: https://github.com/emptyfield-ds/r_packages_setup
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_setup
4. R Packages: Write code
* Rendered material: https://github.com/emptyfield-ds/r_packages_write_code
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_write_code
5. R Packages: Document R Code
* Rendered material: https://github.com/emptyfield-ds/r_packages_document
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_document
6. R Packages: Test R Code
* Rendered material: https://github.com/emptyfield-ds/r_packages_test
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_test
7. Teach your R package
* Rendered material: https://github.com/emptyfield-ds/r_packages_teach
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_teach
8. Add data and files to R packages
* Rendered material: https://github.com/emptyfield-ds/r_packages_add_files
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_add_files
9. R Packages: What's next
* Rendered material: https://github.com/emptyfield-ds/r_packages_whats_next
* Raw material: https://github.com/emptyfield-ds/r_teaching_warehouse/tree/main/r_packages_whats_next

**Comment by malcolmbarrett** [comment]
I forgot to mention: each rendered repo also has a matching RStudio Cloud project with the material and dependencies. I need to vet them and the exercises to make sure everything is correct still but plan to do that soon.

Cloud versions are particularly helpful with pkg dev workshops since occasionally even simple R packages don't cooperate with the user's local setup

**Comment by malcolmbarrett** [comment]
OK, I had a moment to vet all the content and the RStudio Cloud environments. Cleaned things up a bit and now everything should be in more-or-less final condition. 

Happy new year!

**Comment by dgkeyes** [comment]
Thanks, Malcolm! I'm with kids but I'll respond to your work next week!

**Comment by malcolmbarrett** [comment]
No hurry! Enjoy kid time. Just wanted to get these to you by year's end

**Comment by dgkeyes** [comment]
These look great! Since they match what you had showed me before (which I really liked), we can call this good. I'll close this and all other issues in this milestone.

The next step will be to have you record a sample lesson (#12). I'll put some comments there.
