### ISSUE TITLE
Record sample lesson video

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/package-development-course#32]

**Comment by dgkeyes** [comment]
You're on a Mac, right, @malcolmbarrett? If so, I've been purchasing licenses of [Screenflow](https://www.telestream.net/screenflow/overview.htm) for course creators. It's helpful because you can easily record your screen and a video of your face as separate tracks. This makes things easier for my video editor. Let me know if you're on a Mac and, if so, I'll send you the license info for Screenflow.

**Comment by malcolmbarrett** [comment]
I have and use Screenflow already, so no need!

**Comment by dgkeyes** [comment]
Awesome! Please feel free to go ahead and record a sample lesson (you can upload it into [this folder](https://drive.google.com/drive/folders/1eDEYp--eMdZsh7X0BMv3fid2u0Eou0mO?usp=sharing)). I'll do some editing on it and share it with. you so we can make sure it looks good. After that, we can have you move forward recording the other lessons.

**Comment by malcolmbarrett** [comment]
Uploading now! I only did the most basic of editing to trim off junk

**Comment by dgkeyes** [comment]
This looks great overall! I did a quick edit on the video, which you can see [here](https://muse.ai/v/YsKGmt7).

A few things I'm thinking about:

The aspect ratio of your slides appears to be 4:3. At first, I thought this was problematic because we can't do a full screen in the 16:9 ratio I make videos in, but I then did some editing in a way that I think works pretty well with you on the side of the slides. I may just need to zoom in on a few slides to make them 16:9.

![CleanShot 2022-02-08 at 19 45 59](https://user-images.githubusercontent.com/13971585/153118065-f784364b-455c-4f5a-ba4c-af5675938a52.png)

If you can include the video track of your webcam when you do the coding, that would be great. I may want to intersperse you talking with the code. 

In general, feel free to do as little editing as you'd like. I typically just record each lesson in one session and say things on the video like, "that take was bad, please don't use it in the final cut." I'll then edit per your requests.

**Comment by dgkeyes** [comment]
Hey @malcolmbarrett just checking in on this! Do you have any questions? Any sense when you might have time to record other videos? Thanks!
